title: OpenShift Do
project_name: Odo
description: >
  OpenShift Do
repository_url: https://github.com/redhat-developer/odo
repository_shorthand: redhat-developer/odo

home_url: https://redhat-developer.github.io/odo/

author_name: Copyright ©2018 Red Hat, Inc.
author_url: https://github.com/redhat-developer/odo/graphs/contributors

license: Odo (OpenShift Do) is an Apache 2.0 project.
copyright: Copyright ©2018 Red Hat, Inc.

markdown: kramdown

docs_index: /getting-started

plugins:
  - jekyll-redirect-from
